# Generated by Django 3.2.12 on 2023-01-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkFulfillmentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('definition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementNetworkFulfillmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('entity_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versions.entityrequirements')),
                ('network_fulfillment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versions.networkfulfillmentmodels')),
            ],
        ),
        migrations.AddField(
            model_name='networkfulfillmentmodels',
            name='entities_requirement',
            field=models.ManyToManyField(through='versions.RequirementNetworkFulfillmentModel', to='versions.EntityRequirements'),
        ),
    ]
